// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2q-aveUmMIj0DnyuFXExymBiM49lufmg',
    appId: '1:97567392477:web:05bf09e4a26a9c225c9134',
    messagingSenderId: '97567392477',
    projectId: 'prueba-1e69e',
    authDomain: 'prueba-1e69e.firebaseapp.com',
    storageBucket: 'prueba-1e69e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbelvdQMoImljrA-1DiFT6KPbUUNkmYyI',
    appId: '1:97567392477:android:2ca3637cf68d0aa65c9134',
    messagingSenderId: '97567392477',
    projectId: 'prueba-1e69e',
    storageBucket: 'prueba-1e69e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIpPvGwxl4qBZbJDRnnpuwRerW-Af0_Mo',
    appId: '1:97567392477:ios:39e39b3777ebdee05c9134',
    messagingSenderId: '97567392477',
    projectId: 'prueba-1e69e',
    storageBucket: 'prueba-1e69e.appspot.com',
    iosBundleId: 'com.example.pruebaCubit',
  );
}
